#!/bin/sh

### BEGIN INIT INFO
# Provides:             oz
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         1
# Short-Description:    GermansMedia Oz launch processes
### END INIT INFO

case "$1" in
  start)
        /usr/oz/start.sh
        ;;
esac
