#!/bin/sh

### BEGIN INIT INFO
# Provides:             robokind
# Required-Start:       $remote_fs $syslog $qpidd
# Required-Stop:        $remote_fs $syslog $qpidd
# Default-Start:        2 3 4 5
# Default-Stop:         1
# Short-Description:    Hanson Robokind launch processes
### END INIT INFO

case "$1" in
  start)
        /usr/robokind/launch/launch.sh
        ;;
esac
